# Generated by Django 5.2.13 on 2026-04-21 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('forex', 'Forex'), ('index', 'Index'), ('commodity', 'Commodity')], max_length=20)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('direction', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=5)),
                ('is_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('ma_crossover', '5d/20d MA crossover'), ('pct_move_3d', '3-day percentage move'), ('volatility_spike', 'Volatility spike')], max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WATCHLIST', 'Watchlist'), ('ELEVATED', 'Elevated')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('signal_timestamp', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_signals', to='monitoring.asset')),
            ],
            options={
                'ordering': ['-signal_timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceOHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('source', models.CharField(choices=[('twelve', 'Twelve Data'), ('yahoo', 'Yahoo Finance'), ('demo_seed', 'Demo Seed')], default='twelve', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc_data', to='monitoring.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='monitoring.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='monitoring.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset__symbol'],
                'constraints': [models.UniqueConstraint(fields=('user', 'asset'), name='unique_watchlist_item_per_user_asset')],
            },
        ),
    ]
