# Generated by Django 5.2.4 on 2025-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="data_source",
            field=models.CharField(
                choices=[("TWELVE", "Twelve Data"), ("BINANCE", "Binance")],
                default="TWELVE",
                max_length=10,
            ),
        ),
    ]
