# Generated by Django 5.2.4 on 2025-07-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_asset_data_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="account",
        ),
        migrations.AlterUniqueTogether(
            name="pricehistory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="pricehistory",
            name="asset",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="price",
            new_name="entry_price",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="timestamp",
            new_name="opened_at",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="side",
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("crypto", "Cryptocurrency"),
                    ("forex", "Forex"),
                    ("index", "Index"),
                    ("commodity", "Commodity"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="exit_price",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=4
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("above", "Above"), ("below", "Below")], max_length=5
                    ),
                ),
                ("is_triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="monitoring.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="PriceHistory",
        ),
    ]
