# Generated by Django 5.2.4 on 2025-07-11 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_remove_trade_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
            ),
        ),
    ]
