# Generated by Django 5.2.4 on 2025-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_priceohlc"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
