# Generated by Django 5.2.4 on 2025-07-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0008_trade_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
