# Generated by Django 5.2.4 on 2025-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0009_alert_is_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceohlc",
            name="volume",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
