# Generated by Django 5.2.4 on 2025-07-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0010_priceohlc_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceohlc",
            name="source",
            field=models.CharField(
                choices=[("twelve", "Twelve Data"), ("yahoo", "Yahoo Finance")],
                default="twelve",
                max_length=10,
            ),
        ),
    ]
