# Generated by Django 6.0.4 on 2026-04-18 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_priceohlc_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-opened_at']},
        ),
        migrations.CreateModel(
            name='MarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('ma_crossover', '5d/20d MA crossover'), ('pct_move_3d', '3-day percentage move'), ('volatility_spike', 'Volatility spike')], max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WATCHLIST', 'Watchlist'), ('ELEVATED', 'Elevated')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(blank=True)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('signal_timestamp', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_signals', to='monitoring.asset')),
            ],
            options={
                'ordering': ['-signal_timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='monitoring.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset__symbol'],
                'constraints': [models.UniqueConstraint(fields=('user', 'asset'), name='unique_watchlist_item_per_user_asset')],
            },
        ),
    ]
